<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GodotDisabledSourceGenerators>GodotPluginsInitializer</GodotDisabledSourceGenerators>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../../SasukeIroncladCode/MainFile.cs" Link="MainFile.cs" />
    <Compile Include="../../SasukeIroncladCode/Runtime/**/*.cs" Link="Runtime/%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="../../SasukeIroncladCode/Adapters/**/*.cs" Link="Adapters/%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="../../SasukeIroncladCode/Visuals/**/*.cs" Link="Visuals/%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="Sts2ModdingStubs.cs" Link="Sts2ModdingStubs.cs" />
  </ItemGroup>
</Project>